SELECT DISTINCT
    CL.SOURCE_SYSTEM,
    CL.CLAIM_NUMBER,
    CF.SUB_CLAIM_NUMBER AS CLAIM_FEATURE,
    CL.LOSS_DATE,
    CL.REPORTED_TO_INSURER_DATE,
    CS.CLAIM_STATUS_DESCRIPTION,
    CL.LOSS_DESCRIPTION,
    CF.LOSS_TYPE,
    CF.CAUSE_OF_LOSS,
    CL.OPEN_DATE,
    CL.CLOSED_DATE,
    LE.LEGAL_ENTITY_NAME AS COMPANY_NAME,
    CLMNT.CLAIMANT_NAME,
    CONCAT(CLMNT.CLAIMANT_ADDRESS_LINE_1, CLMNT.CLAIMANT_ADDRESS_LINE_2, CLMNT.CLAIMANT_ADDRESS_LINE_3) AS CLAIMANT_ADDRESS,
    CLMNT.CLAIMANT_ADDRESS_CITY,
    CLMNT.CLAIMANT_ADDRESS_STATE,
    CLMNT.CLAIMANT_ADDRESS_POSTAL_CODE,
    CLMNT.CLAIMANT_ADDRESS_COUNTRY,
    CL.JURISDICTION_STATE,
    ADJ.ADJUSTER_NAME,
    COV.PRODUCT_LINE_CDS_CODE AS PRODUCER_ID,
    COV.PRODUCT_LINE_CDS_NAME AS PRODUCER_NAME,
    CASE WHEN CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RESADJIND', 'RESADJEXP') THEN CT.RESERVE_AMOUNT END AS LOSS_RESERVE,
    CASE WHEN CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RESADJEXP') THEN CT.RESERVE_AMOUNT END AS EXPENSE_RESERVE,
     CASE WHEN CT.CLAIM_TRANSACTION_TYPE_CODE IN ('PAYIND', 'PAYEXP') THEN CT.RESERVE_AMOUNT END AS LOSS_PAID,
    CASE WHEN CT.CLAIM_TRANSACTION_TYPE_CODE IN ('PAYEXP') THEN CT.RESERVE_AMOUNT END AS EXPENSE_PAID
    FROM
EDW.EDW.CLAIM_TRANSACTION CT
INNER JOIN
EDW.EDW.CLAIM CL
    ON CT.CLAIM_KEY = CL.CLAIM_KEY
    AND CL.CLAIM_ID = CT.CLAIM_ID
    AND CL.SOURCE_SYSTEM = CT.SOURCE_SYSTEM
    AND YEAR(CT.SYSTEM_END_DATE) = '9999'
INNER JOIN
    EDW.EDW.CLAIM_FEATURE CF
    ON CT.SOURCE_SYSTEM = CF.SOURCE_SYSTEM
    AND CT.CLAIM_KEY = CF.CLAIM_KEY
    AND CT.CLAIM_FEATURE_KEY = CF.CLAIM_FEATURE_KEY
    AND YEAR(CF.SYSTEM_END_DATE) = '9999'
LEFT JOIN EDW.EDW.CLAIM_STATUS CS
    ON CS.SOURCE_SYSTEM = CT.SOURCE_SYSTEM
    AND CS.SOURCE_SYSTEM_KEY = CT.SOURCE_SYSTEM_KEY
    AND CS.CLAIM_STATUS_KEY = CL.CLAIM_STATUS_KEY
    AND CS.CLAIM_STATUS_ID = CL.CLAIM_STATUS_ID
    AND YEAR(CS.SYSTEM_END_DATE) = '9999'
LEFT JOIN EDW.EDW.LEGAL_ENTITY LE
    ON LE.SOURCE_SYSTEM = CT.SOURCE_SYSTEM
    AND LE.SOURCE_SYSTEM_KEY = CT.SOURCE_SYSTEM_KEY
    AND LE.LEGAL_ENTITY_KEY = CL.LEGAL_ENTITY_KEY
    AND LE.LEGAL_ENTITY_ID = CL.LEGAL_ENTITY_ID
    AND YEAR(LE.SYSTEM_END_DATE) = '9999'
LEFT JOIN EDW.EDW.CLAIMANT CLMNT
    ON CLMNT.SOURCE_SYSTEM = CT.SOURCE_SYSTEM
    AND CLMNT.SOURCE_SYSTEM_KEY = CT.SOURCE_SYSTEM_KEY
    AND CLMNT.CLAIM_KEY = CT.CLAIM_KEY
    AND CLMNT.CLAIMANT_KEY = CT.CLAIMANT_KEY
    AND YEAR(CLMNT.SYSTEM_END_DATE) = '9999'
LEFT JOIN EDW.EDW.CLAIM_COVERAGE COV
    ON COV.SOURCE_SYSTEM = CT.SOURCE_SYSTEM
    AND COV.CLAIM_ID = CT.CLAIM_ID
    AND COV.CLAIM_KEY = CT.CLAIM_KEY
    AND COV.CLAIM_COVERAGE_KEY = CT.CLAIM_COVERAGE_KEY
    AND YEAR(COV.SYSTEM_END_DATE) = '9999'
LEFT JOIN EDW.EDW.CLAIM_ADJUSTER ADJ
    ON ADJ.SOURCE_SYSTEM = CT.SOURCE_SYSTEM
    AND ADJ.SOURCE_SYSTEM_KEY = CT.SOURCE_SYSTEM_KEY
    AND ADJ.CLAIM_KEY = CT.CLAIM_KEY
    AND ADJ.CLAIM_ID = CT.CLAIM_ID
    AND YEAR(ADJ.SYSTEM_END_DATE) = '9999'
WHERE CT.SOURCE_SYSTEM = 'GB_ENSTAR'
ORDER BY CL.CLAIM_NUMBER;