SELECT DISTINCT
    CL.SOURCE_SYSTEM,
    CL.CLAIM_NUMBER,
    CF.SUB_CLAIM_NUMBER AS CLAIM_FEATURE,
    CL.LOSS_DATE,
    CL.REPORTED_TO_INSURER_DATE,
    CS.CLAIM_STATUS_DESCRIPTION,
    CL.LOSS_DESCRIPTION,
    CF.LOSS_TYPE,
    CF.CAUSE_OF_LOSS,
    CL.OPEN_DATE,
    CL.CLOSED_DATE,
    CF.FEATURE_CLOSED_DATE,
    COV.COVERAGE_STATUS,
    CVBL.COVERABLE_STATUS,
    COV.CLAIM_COVERAGE_CODE AS COVERAGE_CODE,
    CL.LEGAL_ENTITY_CDS,
    LE.LEGAL_ENTITY_NAME AS COMPANY_NAME,
    CLMNT.CLAIMANT_NAME,
    CONCAT(CLMNT.CLAIMANT_ADDRESS_LINE_1, CLMNT.CLAIMANT_ADDRESS_LINE_2, CLMNT.CLAIMANT_ADDRESS_LINE_3) AS CLAIMANT_ADDRESS,
    CLMNT.CLAIMANT_ADDRESS_CITY,
    CLMNT.CLAIMANT_ADDRESS_STATE,
    CLMNT.CLAIMANT_ADDRESS_POSTAL_CODE,
    CLMNT.CLAIMANT_ADDRESS_COUNTRY,
    CONCAT(CVBL.COVERABLE_ADDRESS_LINE_1, CVBL.COVERABLE_ADDRESS_LINE_2, CVBL.COVERABLE_ADDRESS_LINE_3) AS LOSS_ADDRESS,
    CVBL.COVERABLE_ADDRESS_CITY AS LOSS_CITY,
    CVBL.COVERABLE_ADDRESS_POSTAL_CODE AS LOSS_ZIP,
    CVBL.COVERABLE_ADDRESS_COUNTRY AS LOSS_COUNTRY,
    CL.ACCIDENT_STATE AS LOSS_STATE,
    COV.ACCIDENT_YEAR AS LOSS_YEAR,
    CAT.CATASTROPHE_CODE AS CAT_CODE,
    CAT.CATASTROPHE_ISO_CODE,
    CAT.CATASTROPHE_LOCATION,
    CAT.CATASTROPHE_DESCRIPTION,
    CT.CLAIM_TRANSACTION_TYPE_CODE,
    CL.JURISDICTION_STATE,
    ADJ.CLAIM_ADJUSTER_KEY,
    ADJ.ADJUSTER_NAME,
    COV.ANNUAL_STATEMENT_LINE_OF_BUSINESS,
    COV.PRODUCT_LINE_CDS_CODE AS PRODUCER_ID,
    COV.PRODUCT_LINE_CDS_NAME AS PRODUCER_NAME,
    CL.CLAIM_SUPERVISOR AS SUPERVISOR_NAME,
    CVBL.CLASS_CODE,
    CVBL.CLASS_CODE_DESCRIPTION,
    SUM(CASE 
        WHEN ct.CLAIM_TRANSACTION_TYPE_CODE IN ('RESCLSNCEEXP', 'RESADJEXPNCE', 'INITRESEXPNCE', 'PAYEXPNCE') 
            THEN ct.PAYMENT_AMOUNT + ct.RESERVE_AMOUNT 
        ELSE 0 
    END) AS NCE_INCURRED_AMT,
    SUM(CASE 
        WHEN ct.CLAIM_TRANSACTION_TYPE_CODE IN ('PAYEXPNCE') 
            THEN ct.PAYMENT_AMOUNT 
        ELSE 0 
    END) AS NCE_PAID_AMT,
    SUM(CASE 
        WHEN ct.CLAIM_TRANSACTION_TYPE_CODE IN ('INITRESIND','INITRESEXP','INITRESEXPNCE','RESADJIND','RESADJEXP','RESADJEXPNCE') 
            THEN ct.RESERVE_AMOUNT 
        ELSE 0 
    END) AS TOTAL_INCURRED,
    SUM(CASE 
        WHEN ct.CLAIM_TRANSACTION_TYPE_CODE IN ('PAYEXP','PAYIND','PAYEXPNCE') 
            THEN ct.PAYMENT_AMOUNT 
        ELSE 0 
    END) AS TOTAL_PAID,
    SUM(CASE 
    	WHEN UPPER(CT.SOURCE_SYSTEM) LIKE 'GB_ENSTAR%'  
        AND SUBSTR(CL.CLAIM_NUMBER ,1,1)  NOT IN ('L','P') 
        AND CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RESADJIND','PAYIND') 
            THEN CT.RESERVE_AMOUNT 
    	WHEN UPPER(CT.SOURCE_SYSTEM) LIKE 'GB_ENSTAR%'  
        AND SUBSTR(CL.CLAIM_NUMBER ,1,1)  IN ('L','P') 
        AND CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RECDEDIND','RECSUBIND','RECSALIND','RECOTHIND') 
            THEN CT.PAYMENT_AMOUNT
    	WHEN UPPER(CT.SOURCE_SYSTEM) LIKE 'GB_ENSTAR%'  
        AND SUBSTR(CL.CLAIM_NUMBER ,1,1)  IN ('L','P') 
        AND CT.CLAIM_TRANSACTION_TYPE_CODE IN ('PAYIND', 'RESADJIND') 
            THEN CT.RESERVE_AMOUNT
    	WHEN UPPER(CT.SOURCE_SYSTEM) != 'GB_ENSTAR'  
        AND CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RESADJIND', 'RESADJEXP')
            THEN CT.RESERVE_AMOUNT
        ELSE 0 
    END) AS LOSS_RESERVE,
    SUM(CASE 
    	WHEN UPPER(CT.SOURCE_SYSTEM) LIKE 'GB_ENSTAR%'  
        AND SUBSTR(CL.CLAIM_NUMBER ,1,1)  NOT IN ('L','P') 
        AND CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RESADJEXP','PAYEXP')  
            THEN CT.RESERVE_AMOUNT 
    	WHEN UPPER(CT.SOURCE_SYSTEM) LIKE 'GB_ENSTAR%'  
        AND SUBSTR(CL.CLAIM_NUMBER ,1,1)  IN ('L','P') 
        AND CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RECDEDEXP','RECSUBEXP','RECSALEXP','RECOTHEXP') 
            THEN CT.PAYMENT_AMOUNT
    	WHEN UPPER(CT.SOURCE_SYSTEM) LIKE 'GB_ENSTAR%'  
        AND SUBSTR(CL.CLAIM_NUMBER ,1,1)  IN ('L','P') 
        AND CT.CLAIM_TRANSACTION_TYPE_CODE IN ('PAYEXP', 'RESADJEXP') THEN CT.RESERVE_AMOUNT
    	WHEN UPPER(CT.SOURCE_SYSTEM) != 'GB_ENSTAR'   
        AND CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RESADJEXP') 
            THEN CT.RESERVE_AMOUNT
        ELSE 0
        END) AS EXPENSE_RESERVE,
    SUM(CASE 
    	WHEN UPPER(CT.SOURCE_SYSTEM) LIKE 'GB_ENSTAR%'  
        AND SUBSTR(CL.CLAIM_NUMBER ,1,1)  NOT IN ('L','P') 
        AND CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RESADJEXP','PAYEXP')  
            THEN CT.RESERVE_AMOUNT 
    	WHEN UPPER(CT.SOURCE_SYSTEM) LIKE 'GB_ENSTAR%'  
        AND SUBSTR(CL.CLAIM_NUMBER ,1,1)  IN ('L','P') 
        AND CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RECDEDEXP','RECSUBEXP','RECSALEXP','RECOTHEXP') 
            THEN CT.PAYMENT_AMOUNT
    	WHEN UPPER(CT.SOURCE_SYSTEM) LIKE 'GB_ENSTAR%'  
        AND SUBSTR(CL.CLAIM_NUMBER ,1,1)  IN ('L','P') 
        AND CT.CLAIM_TRANSACTION_TYPE_CODE IN ('PAYEXP', 'RESADJEXP') THEN CT.RESERVE_AMOUNT
    	WHEN UPPER(CT.SOURCE_SYSTEM) != 'GB_ENSTAR'   
        AND CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RESADJEXP') 
            THEN CT.RESERVE_AMOUNT
        ELSE 0
        END) AS ALAE_RESERVE,
    SUM(CASE 
        WHEN UPPER(CT.SOURCE_SYSTEM) LIKE 'GB_ENSTAR%'  
        AND CT.CLAIM_TRANSACTION_TYPE_CODE = 'PAYIND' 
            THEN CT.PAYMENT_AMOUNT
        WHEN UPPER(CT.SOURCE_SYSTEM) != 'GB_ENSTAR' 
            AND CT.CLAIM_TRANSACTION_TYPE_CODE IN ('PAYIND', 'PAYEXP') 
            THEN CT.RESERVE_AMOUNT 
        ELSE 0 
        END)  AS LOSS_PAID,
    SUM(CASE 
        WHEN CT.CLAIM_TRANSACTION_TYPE_CODE IN ('PAYEXP') 
            THEN CT.RESERVE_AMOUNT 
        ELSE 0
        END) AS EXPENSE_PAID,
    SUM(CASE 
        WHEN UPPER(CT.SOURCE_SYSTEM) LIKE 'GB_ENSTAR%'  
        AND CT.CLAIM_TRANSACTION_TYPE_CODE = 'PAYEXP' 
            THEN CT.PAYMENT_AMOUNT 
        WHEN UPPER(CT.SOURCE_SYSTEM) != 'GB_ENSTAR'
        AND CT.CLAIM_TRANSACTION_TYPE_CODE IN ('PAYEXP')
            THEN CT.RESERVE_AMOUNT
        ELSE 0 
        END) AS ALAE_PAID,
    SUM(CASE 
        WHEN ct.CLAIM_TRANSACTION_TYPE_CODE IN ('PAYEXPNCE')
            THEN ct.PAYMENT_AMOUNT 
        ELSE 0 
    END) AS ULAE_PAID,
    SUM(CASE 
        WHEN ct.CLAIM_TRANSACTION_TYPE_CODE IN ('INITRESEXPNCE', 'RESADJEXPNCE', 'RESCLSNCEEXP') 
            THEN ct.RESERVE_AMOUNT 
        ELSE 0 
    END) AS ULAE_RESERVE,
    SUM(CASE 
        WHEN CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RECDEDIND','RECSUBIND','RECSALIND','RECOTHIND') 
            THEN CT.PAYMENT_AMOUNT 
        ELSE 0 
    END) AS LOSS_RECOVERY,
    SUM(CASE 
        WHEN CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RECDEDEXP','RECSUBEXP','RECSALEXP','RECOTHEXP') 
            THEN CT.PAYMENT_AMOUNT 
        ELSE 0 
    END) AS EXPENSE_RECOVERY,
    SUM(CASE 
        WHEN CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RECDEDEXP','RECSUBEXP','RECSALEXP','RECOTHEXP') 
            THEN CT.PAYMENT_AMOUNT 
        ELSE 0 
    END) AS ALAE_RECOVERY,
    SUM(CASE 
        WHEN CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RECSALIND','RECSALEXP','RECSALRESADJIND','RECSALRESADJEXP','RECSALRESCLSIND','RECSALRESCLSEXP') 
            THEN CT.PAYMENT_AMOUNT 
        ELSE 0 
    END) AS SALVAGE_RECOVERY,
    SUM(CASE 
        WHEN CT.CLAIM_TRANSACTION_TYPE_CODE IN ('RECSUBIND','RECSUBEXP','RECSUBRESADJIND','RECSUBRESADJEXP','RECSUBRESCLSIND','RECSUBRESCLSEXP') 
            THEN CT.PAYMENT_AMOUNT 
        ELSE 0 
    END) AS SUBRO_RECOVERY
    FROM
EDW.EDW.CLAIM_TRANSACTION CT
INNER JOIN
EDW.EDW.CLAIM CL
    ON CT.CLAIM_KEY = CL.CLAIM_KEY
    AND CL.CLAIM_ID = CT.CLAIM_ID
    AND CL.SOURCE_SYSTEM = CT.SOURCE_SYSTEM
INNER JOIN
    EDW.EDW.CLAIM_FEATURE CF
    ON CT.SOURCE_SYSTEM = CF.SOURCE_SYSTEM
    AND CT.CLAIM_KEY = CF.CLAIM_KEY
    AND CT.CLAIM_FEATURE_KEY = CF.CLAIM_FEATURE_KEY
LEFT JOIN EDW.EDW.CLAIM_STATUS CS
    ON CS.SOURCE_SYSTEM = CT.SOURCE_SYSTEM
    AND CS.SOURCE_SYSTEM_KEY = CT.SOURCE_SYSTEM_KEY
    AND CS.CLAIM_STATUS_KEY = CL.CLAIM_STATUS_KEY
    AND CS.CLAIM_STATUS_ID = CL.CLAIM_STATUS_ID
LEFT JOIN EDW.EDW.LEGAL_ENTITY LE
    ON LE.SOURCE_SYSTEM = CT.SOURCE_SYSTEM
    AND LE.SOURCE_SYSTEM_KEY = CT.SOURCE_SYSTEM_KEY
    AND LE.LEGAL_ENTITY_KEY = CL.LEGAL_ENTITY_KEY
    AND LE.LEGAL_ENTITY_ID = CL.LEGAL_ENTITY_ID
LEFT JOIN EDW.EDW.CLAIMANT CLMNT
    ON CLMNT.SOURCE_SYSTEM = CT.SOURCE_SYSTEM
    AND CLMNT.SOURCE_SYSTEM_KEY = CT.SOURCE_SYSTEM_KEY
    AND CLMNT.CLAIM_KEY = CT.CLAIM_KEY
    AND CLMNT.CLAIMANT_KEY = CT.CLAIMANT_KEY
LEFT JOIN EDW.EDW.CLAIM_COVERAGE COV
    ON COV.SOURCE_SYSTEM = CT.SOURCE_SYSTEM
    AND COV.CLAIM_ID = CT.CLAIM_ID
    AND COV.CLAIM_KEY = CT.CLAIM_KEY
    AND COV.CLAIM_COVERAGE_KEY = CT.CLAIM_COVERAGE_KEY
LEFT JOIN EDW.EDW.CLAIM_COVERABLE CVBL
    ON CVBL.SOURCE_SYSTEM = CT.SOURCE_SYSTEM
    AND CVBL.CLAIM_ID = CT.CLAIM_ID
    AND CVBL.CLAIM_KEY = CT.CLAIM_KEY
    AND CVBL.CLAIM_COVERABLE_KEY = CT.CLAIM_COVERABLE_KEY
LEFT JOIN EDW.EDW.CATASTROPHE CAT
    ON CAT.SOURCE_SYSTEM = CT.SOURCE_SYSTEM
    AND CAT.SOURCE_SYSTEM_KEY = CT.SOURCE_SYSTEM_KEY
    AND CAT.CATASTROPHE_KEY = CL.CATASTROPHE_KEY
    --AND CAT.CATASTROPHE_ID = CL.CATASTROPHE_ID
LEFT JOIN EDW.EDW.CLAIM_ADJUSTER ADJ
    ON ADJ.SOURCE_SYSTEM = CT.SOURCE_SYSTEM
    AND ADJ.SOURCE_SYSTEM_KEY = CT.SOURCE_SYSTEM_KEY
    AND ADJ.CLAIM_KEY = CT.CLAIM_KEY
    AND ADJ.CLAIM_ID = CT.CLAIM_ID
WHERE UPPER(CT.SOURCE_SYSTEM) = 'GB_ENSTAR'
GROUP BY 
    CL.SOURCE_SYSTEM,
    CL.CLAIM_NUMBER,
    CF.SUB_CLAIM_NUMBER,
    CL.LOSS_DATE,
    CL.REPORTED_TO_INSURER_DATE,
    CS.CLAIM_STATUS_DESCRIPTION,
    CL.LOSS_DESCRIPTION,
    CF.LOSS_TYPE,
    CF.CAUSE_OF_LOSS,
    CL.OPEN_DATE,
    CL.CLOSED_DATE,
    CL.LEGAL_ENTITY_CDS,
    LE.LEGAL_ENTITY_NAME,
    CLMNT.CLAIMANT_NAME,
    CONCAT(CLMNT.CLAIMANT_ADDRESS_LINE_1, CLMNT.CLAIMANT_ADDRESS_LINE_2, CLMNT.CLAIMANT_ADDRESS_LINE_3),
    CLMNT.CLAIMANT_ADDRESS_CITY,
    CLMNT.CLAIMANT_ADDRESS_STATE,
    CLMNT.CLAIMANT_ADDRESS_POSTAL_CODE,
    CLMNT.CLAIMANT_ADDRESS_COUNTRY,
    CONCAT(CVBL.COVERABLE_ADDRESS_LINE_1, CVBL.COVERABLE_ADDRESS_LINE_2, CVBL.COVERABLE_ADDRESS_LINE_3),
    CVBL.COVERABLE_ADDRESS_CITY,
    CVBL.COVERABLE_ADDRESS_POSTAL_CODE,
    CVBL.COVERABLE_ADDRESS_COUNTRY,
    CL.ACCIDENT_STATE,
    COV.ACCIDENT_YEAR,
    CAT.CATASTROPHE_CODE,
    CAT.CATASTROPHE_ISO_CODE,
    CAT.CATASTROPHE_LOCATION,
    CAT.CATASTROPHE_DESCRIPTION,
    CT.CLAIM_TRANSACTION_TYPE_CODE,
    CL.JURISDICTION_STATE,
    ADJ.ADJUSTER_NAME,
    COV.PRODUCT_LINE_CDS_CODE,
    COV.PRODUCT_LINE_CDS_NAME,
    CL.CLAIM_SUPERVISOR,
    CF.FEATURE_CLOSED_DATE,
    COV.COVERAGE_STATUS,
    CVBL.COVERABLE_STATUS,
    COV.CLAIM_COVERAGE_CODE,
    ADJ.CLAIM_ADJUSTER_KEY,
    COV.ANNUAL_STATEMENT_LINE_OF_BUSINESS,
    CVBL.CLASS_CODE,
    CVBL.CLASS_CODE_DESCRIPTION
ORDER BY CL.CLAIM_NUMBER;